//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblInvoices = new HashSet<tblInvoice>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
        }
    
        public int CustomerID { get; set; }
        public string BusinessName { get; set; }
        public string ContactName { get; set; }
        public string EMailID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string IntPhoneNo { get; set; }
        public string AirportDestCity { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
    }
}
