//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleInvoice
    {
        public tblSaleInvoice()
        {
            this.tblSaleInvoiceProductDetails = new HashSet<tblSaleInvoiceProductDetail>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
            this.tblBoxLists = new HashSet<tblBoxList>();
        }
    
        public int SaleInvoiceID { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public int InvoiceNo { get; set; }
        public int SaleInvoiceStatusID { get; set; }
        public int CustomerID { get; set; }
        public string BusinessName { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string IntPhoneNo { get; set; }
        public string EmailContact { get; set; }
        public string AirportDestCity { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public string DomesticFlight { get; set; }
        public string InternationalFlight { get; set; }
        public decimal TotalQuan { get; set; }
        public decimal TotalGAmt { get; set; }
        public int EstBoxes { get; set; }
        public decimal BoxCharges { get; set; }
        public decimal DomesticFreightCharges { get; set; }
        public decimal IntFreightCharges { get; set; }
        public decimal TTFee { get; set; }
        public decimal TotalFreight { get; set; }
        public decimal PreviousCredit { get; set; }
        public decimal TotalPayableAmt { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual tblSaleInvoiceStatu tblSaleInvoiceStatu { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual ICollection<tblSaleInvoiceProductDetail> tblSaleInvoiceProductDetails { get; set; }
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
        public virtual ICollection<tblBoxList> tblBoxLists { get; set; }
    }
}
