//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleOrder
    {
        public tblSaleOrder()
        {
            this.tblInvoices = new HashSet<tblInvoice>();
            this.tblSaleOrderProductDetails = new HashSet<tblSaleOrderProductDetail>();
        }
    
        public int SaleOrderID { get; set; }
        public System.DateTime SODate { get; set; }
        public int SONo { get; set; }
        public int CustomerID { get; set; }
        public string AirportDest { get; set; }
        public string EstDelDate { get; set; }
        public decimal TotalQuan { get; set; }
        public decimal TotalAmt { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        public virtual ICollection<tblSaleOrderProductDetail> tblSaleOrderProductDetails { get; set; }
        public virtual tblCustomer tblCustomer { get; set; }
    }
}
