//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleInvoiceStatu
    {
        public tblSaleInvoiceStatu()
        {
            this.tblSaleInvoices = new HashSet<tblSaleInvoice>();
        }
    
        public int SaleInvoiceStatusID { get; set; }
        public string SaleInvoiceStatusName { get; set; }
    
        public virtual ICollection<tblSaleInvoice> tblSaleInvoices { get; set; }
    }
}
