//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleOrderProductDetail
    {
        public int SaleOrderProductDetailID { get; set; }
        public int SaleOrderID { get; set; }
        public int ProductID { get; set; }
        public decimal Rate { get; set; }
        public decimal Quan { get; set; }
        public decimal Amt { get; set; }
    
        public virtual tblSaleOrder tblSaleOrder { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
