//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsersLoginLog
    {
        public int UserLogID { get; set; }
        public int UserID { get; set; }
        public System.DateTime LoginDT { get; set; }
    
        public virtual tblUser tblUser { get; set; }
    }
}
