//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UCAOrderManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblCompanies = new HashSet<tblCompany>();
            this.tblCompanies1 = new HashSet<tblCompany>();
            this.tblInvoices = new HashSet<tblInvoice>();
            this.tblInvoices1 = new HashSet<tblInvoice>();
            this.tblProductCommonNames = new HashSet<tblProductCommonName>();
            this.tblProductCommonNames1 = new HashSet<tblProductCommonName>();
            this.tblProductOpeningStocks = new HashSet<tblProductOpeningStock>();
            this.tblProductOpeningStocks1 = new HashSet<tblProductOpeningStock>();
            this.tblProductRates = new HashSet<tblProductRate>();
            this.tblProductRates1 = new HashSet<tblProductRate>();
            this.tblProductScientificNames = new HashSet<tblProductScientificName>();
            this.tblProductScientificNames1 = new HashSet<tblProductScientificName>();
            this.tblProductSizes = new HashSet<tblProductSize>();
            this.tblProductSizes1 = new HashSet<tblProductSize>();
            this.tblSaleOrders = new HashSet<tblSaleOrder>();
            this.tblSaleOrders1 = new HashSet<tblSaleOrder>();
            this.tblUser1 = new HashSet<tblUser>();
            this.tblUser11 = new HashSet<tblUser>();
            this.tblUsersLoginLogs = new HashSet<tblUsersLoginLog>();
            this.tblUpdateInventoryLogs = new HashSet<tblUpdateInventoryLog>();
            this.tblProducts = new HashSet<tblProduct>();
            this.tblProducts1 = new HashSet<tblProduct>();
        }
    
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string EmailID { get; set; }
        public string Password { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<System.DateTime> rcdt { get; set; }
        public Nullable<int> rcuid { get; set; }
        public Nullable<System.DateTime> redt { get; set; }
        public Nullable<int> reuid { get; set; }
    
        public virtual ICollection<tblCompany> tblCompanies { get; set; }
        public virtual ICollection<tblCompany> tblCompanies1 { get; set; }
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        public virtual ICollection<tblInvoice> tblInvoices1 { get; set; }
        public virtual ICollection<tblProductCommonName> tblProductCommonNames { get; set; }
        public virtual ICollection<tblProductCommonName> tblProductCommonNames1 { get; set; }
        public virtual ICollection<tblProductOpeningStock> tblProductOpeningStocks { get; set; }
        public virtual ICollection<tblProductOpeningStock> tblProductOpeningStocks1 { get; set; }
        public virtual ICollection<tblProductRate> tblProductRates { get; set; }
        public virtual ICollection<tblProductRate> tblProductRates1 { get; set; }
        public virtual ICollection<tblProductScientificName> tblProductScientificNames { get; set; }
        public virtual ICollection<tblProductScientificName> tblProductScientificNames1 { get; set; }
        public virtual ICollection<tblProductSize> tblProductSizes { get; set; }
        public virtual ICollection<tblProductSize> tblProductSizes1 { get; set; }
        public virtual ICollection<tblSaleOrder> tblSaleOrders { get; set; }
        public virtual ICollection<tblSaleOrder> tblSaleOrders1 { get; set; }
        public virtual ICollection<tblUser> tblUser1 { get; set; }
        public virtual tblUser tblUser2 { get; set; }
        public virtual ICollection<tblUser> tblUser11 { get; set; }
        public virtual tblUser tblUser3 { get; set; }
        public virtual tblUserRole tblUserRole { get; set; }
        public virtual ICollection<tblUsersLoginLog> tblUsersLoginLogs { get; set; }
        public virtual ICollection<tblUpdateInventoryLog> tblUpdateInventoryLogs { get; set; }
        public virtual ICollection<tblProduct> tblProducts { get; set; }
        public virtual ICollection<tblProduct> tblProducts1 { get; set; }
    }
}
